### ISSUE TITLE
SQLite Compression

### ISSUE THREAD

**Issue by indolering** [namecoin/libcoin#11]
With FS-level compression, we are able to get a dust-free SqliteDB down to ~200 megs.  However, Android and iOS do not offer FS-level compression.

The authors of SQLite offer [a compression solution](http://www.hwaci.com/sw/sqlite/zipvfs.html).  The perpetual source license is only $2,000 but it is unclear if we could post the source publicly.

I was able to find a single, non-commercial transparent compression [solution](http://blog.ashodnakashian.com/2011/09/sqlite-with-built-in-online-compression/) but it fundamentally relies on NTFS compression and only hints at a cross-platform solution.  However, their compression numbers suggest we could get the DB to even less than 200 megs.

**Comment by domob1812** [comment]
TBH, I'm not sure if this is really worth the effort.  Storage is cheap, and will get cheaper over time.  "Just" saving 50% (as opposed to an order of magnitude or something) seems not really too much - given the deep changes necessary to implement compression.  But if you think it is necessary, you should open a ticket against libcoin/libcoin.  This is more related to libcoin proper than it is to Namecoin-specific aspects of it, IMHO.

**Comment by indolering** [comment]
@domob1812 that was fast.  Yeah, I agree, time might make this irrelevant.

**Comment by JeremyRand** [comment]
I agree with @domob1812.  Also, this should be done on the level of individual names, for 2 reasons: (1) it will still work with encryption, and (2) it will provide a clear incentive for name owners to use compressible values, since they'll be able to fit more into a single 520-byte value.

**Comment by indolering** [comment]
@JeremyRand the names database makes up ~30 megs, I'm trying to get the DB down to the 200MB range.

**Comment by JeremyRand** [comment]
@indolering I suspect (though I have no proof) that this is primarily because Namecoin is being widely misused as a speculative currency rather than as a naming system.  Once naming is the primary use case, I think that will change.

Other than that, I think if FS-level compression is good enough, then there's no reason for us to re-implement it.  Users of filesystems which don't support compression should consider switching filesystems if they want that functionality.

**Comment by indolering** [comment]
@JeremyRand discussion compression of names at the blockchain level is irrelevant here.

I'm also not suggesting that we need to solve this in the immediate future, however, if someone wants to create an Android or iPhone lite-client using Libcoin they **will** need to implement compression in SQLite.

This ticket serves as a placeholder for a BountySource bounty as well as technical discussion regarding this solution.

**Comment by JeremyRand** [comment]
Closed as wontfix due to https://github.com/namecoin/libcoin/issues/20
