### ISSUE TITLE
Misc Storage Optimizations

### ISSUE THREAD

**Issue by indolering** [namecoin/libcoin#12]
Trivial changes that yield >50% space savings:
- [ ] A full `vacuum` optimization after the initial block-chain sync.
- [ ] Enabling auto-vacuum after the initial `vacuum` optimization.
- [ ] Enable FS-level compression on the .namecoin directory on filesystems that support it.

**Comment by JeremyRand** [comment]
Closed as wontfix due to https://github.com/namecoin/libcoin/issues/20
