### ISSUE TITLE
Fix dust spam

### ISSUE THREAD

**Issue by indolering** [namecoin/libcoin#13]
Removing all 1 Satoshi outputs before block 50k would remove the majority of the dust-spam from the system.

[Mainline Ticket](https://github.com/namecoin/namecoin/issues/139)
[Mainline PR](https://github.com/namecoin/namecoin/pull/140)
[Forum cross-reference](https://forum.namecoin.info/viewtopic.php?f=2&t=1877&p=12149#p12149)

**Comment by JeremyRand** [comment]
Closed as wontfix due to https://github.com/namecoin/libcoin/issues/20
