### ISSUE TITLE
Mark remaining issues as wontfix

### ISSUE THREAD

**Issue by JeremyRand** [namecoin/libcoin#20]
Upstream libcoin appears unmaintained (no commits in almost a year), and we're not actively using that code for anything at the moment since we're using Namecoin Core.  I therefore suggest that we close the remaining Namecoin libcoin issues as wontfix, since our development time is better spent on Namecoin Core (which has an actively developed upstream).

**Comment by JeremyRand** [comment]
Opinions @domob1812 @phelixbtc ?

**Comment by domob1812** [comment]
ACK.

**Comment by JeremyRand** [comment]
The affected issues have been closed as wontfix; closing this.
