### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by venzen** [namecoin/libcoin#3]
compilation fails on ponzicoin.o with the following error:

```
/libcoin/examples/ponzicoin/ponzicoin.cpp: At global scope:
/libcoin/examples/ponzicoin/ponzicoin.cpp:197:18: error: cannot declare variable ‘ponzicoin’ to be of abstract type ‘PonziChain’
 const PonziChain ponzicoin;
              ^
/libcoin/examples/ponzicoin/ponzicoin.cpp:42:7: note:   because the following virtual functions are pure within ‘PonziChain’:
 class PonziChain : public Chain
```

**Comment by domob1812** [comment]
This repository is out of date.  You should probably use the official one libcoin/libcoin.  I don't know what the plans are in the future of maintaining this one or not - but for now, libcoin/libcoin contains everything including my work on adding Namecoin RPC commands so far.

**Comment by venzen** [comment]
@domob1812 Thanks for the reply.

Could you perhaps indicate how you run namecoind from libcoin? As in which file(s) with which option?

I've managed to compile libcoin but the codebase is not happy - it is riddled with inconsistencies and compilation errors - and the author does not indicate exactly which platform and libraries he runs on, so it is pretty much useless as a library - brilliant as the idea is.

I'm keen on experimenting with the Namecoin implementation of libcoin, and assume you've gotten this to work, so any pointers or advice will be much appreciated.

**Comment by domob1812** [comment]
You can take a look at my https://github.com/domob1812/nmc-libcoin repository.  If you have libcoin built & installed, you can build this one.  It includes a Shell script "run.sh" that handles some of the options you have to use.

But in general, you don't need that.  Just building libcoin alone should be enough to experiment - what you need to run is the binary produced in "bin/libcoind".  Pass it the "--namecoin" option, and potentially also "--persistence FULL" - this disables the built-in blockchain pruning so that it behaves as a full node comparable to namecoind.  I. e.,

bin/libcoind --persistence FULL --namecoin

is what works for me.  If you want to call RPC routines, just add them to the command.

**Comment by venzen** [comment]
Thank you very much. It works.

I'm just getting my head around this library via the wiki and a pdf i found at repticle.com...

Looking at your code at https://github.com/domob1812/nmc-libcoin it seems you had built namecoin from scratch in main.cpp (although I don't see the name operations defined).

Yet, in the libcoin code, Namecoin's definition and name methods are cast as a library, presumably in include/coin/NameOperation.h and elsewhere?

**Comment by venzen** [comment]
BTW, running `./configure` on the sources of the repo quoted above, and having libboost1.48-dev-all installed, i get:

./configure: line 2972: syntax error near unexpected token `1.48,,'
./configure: line 2972:`AX_BOOST_BASE(1.48,, AC_MSG_ERROR([nmc-libcoin needs Boost, but it was not found in your system]))'

Any idea?

**Comment by domob1812** [comment]
The main implementation is in the library (in the various include/ and source/ folders).  Both my nmc-libcoin repository and the libcoind binary (whose source is applications/libcoind/libcoind.cpp) are just light applications using the library to implement a daemon and client.

In fact, nmc-libcoin is based heavily on libcoind.cpp.  Currently, it doesn't really do anything more than libcoind (it registers the new name_show RPC command which was not present in libcoind until some time ago, but I think now name_show is also available from libcoind directly).  But it may be adapted in the future, for instance, to not require --namecoin or with other customisations.

**Comment by venzen** [comment]
Thanks for the reply and explanation - it has really provided some clarity for me to get going.

Regarding the AX_BOOST_BASE issue above i've looked at http://www.gnu.org/software/autoconf-archive/ax_boost_base.html#ax_boost_base and http://www.gnu.org/software/autoconf-archive/ax_boost_base.html#ax_boost_base
which led me to create subdir m4 with the ax_boost_base.m4 macro in there. 
I see you've specified `AC_CONFIG_MACRO_DIR([m4])` in _configure.ac_ and `ACLOCAL_AMFLAGS = -I m4` in _Makefile.am_ but the error persists. 
Is there some way to just point the configure script at the BOOST_ROOT /usr/lib/x86_64-linux-gnu without AX_BOOST_BASE version checking, which seems broken?

_edit:_ some elbow grease got it compiled

**Comment by domob1812** [comment]
For me (on Ubuntu and Debian systems), this macro is provided by the "autoconf-archive" package (installing just autoconf is not enough).  I don't know about others.

**Comment by domob1812** [comment]
Can we close this?

**Comment by JeremyRand** [comment]
@domob1812 FWIW, I can build libcoind but not nmc-libcoin... nmc-libcoin gives me some weird build errors that I was meaning to report but never had the time to do so.  But, probably better to make that a separate issue, so I'm fine with closing this.

**Comment by domob1812** [comment]
Closing this.  There's been a lot of changes to libcoin since then, please reopen a new issue if other compilation errors occur.
