### ISSUE TITLE
Testnet

### ISSUE THREAD

**Issue by indolering** [namecoin/libcoin#6]
Get testnet working on Libcoin.

**Comment by domob1812** [comment]
I've pushed jonasbits' experimental code to the `namecoin-testnet-beta` branch.  It works so far, but includes some hacks to make it work that need further evaluation.

**Comment by JeremyRand** [comment]
Closed as wontfix due to https://github.com/namecoin/libcoin/issues/20

**Comment by pocketwalker** [comment]
so how to set up a testnet namecoind now?
