### ISSUE TITLE
Read-only RPC calls

### ISSUE THREAD

**Issue by indolering** [namecoin/libcoin#8]
Namely `name_scan` and `name_filter`.

These _should_ just be a matter of writing some SQL queries.

**Comment by domob1812** [comment]
`name_filter` and `name_scan` yes, `name_list` is different since it relies on the user's wallet.

**Comment by indolering** [comment]
Okay, I've moved `name_list` but I'll keep it off of the lite-client radar.

**Comment by domob1812** [comment]
`name_list` is now supported after I pushed the recent upstream changes (including my `name_list` patch) to namecoin/libcoin.
